### PR TITLE
waf: use ConfigSet for board environments

### PR DESCRIPTION
**Pull request by cmarcelo**
Instead of a dictionary of dictionaries, have a dictionary of
ConfigSets. Using ConfigSet have two benefits: (1) allow easily copying
values from other, (2) have syntax for specifying the keys directly as
attributes.

With this change now it's easier to specify minlure without
repetition. New boards can override a value or append/prepend using
ConfigSet syntax.

A helper function redefine() was added to allow easily overriding
certain parameters in the defines list.

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
Overall I like it.

**Comment by guludo** [comment]
> Would setting env.CC/env.CXX here work (if it was not set in the command line...)?

@lucasdemarchi I have already a WIP on that.

**Comment by guludo** [comment]
> don't you have a problem here that now setup_boards() is a target for waf and it's listed in waf --help?

I think it will be listed only if it has a docstring. But `waf setup_boards` would unsuccessfully try to call that function.

**Comment by guludo** [comment]
> I think we should already think how to handle navio/bebop/etc that by default expects another compiler. Would setting env.CC/env.CXX here work (if it was not set in the command line...)?

What I have in the WIP already selects the correct toolchain, however I'm getting a compiler segfault error when building :/

**Comment by cmarcelo** [comment]
> I think it will be listed only if it has a docstring. But waf setup_boards would unsuccessfully try to call > that function.

Bad waf :(  This is an issue with all toplevel things. I'm asking whether there's a solution, otherwise we can simply throw them at `ardupilotwaf.py`.

**Comment by cmarcelo** [comment]
@guludo 

> Looks more elegant and is self contained. I don't have a problem with using the += operator, but I > don't like the use of redefine(). If you don't like the extra code to allow such call constructions:
> 
>  board.DEFINES(
>         CONFIG_HAL_BOARD='HAL_BOARD_SITL',
>         CONFIG_HAL_BOARD_SUBTYPE='HAL_BOARD_SUBTYPE_NONE',
>     )
> 
>    board.CXXFLAGS(
>        '-O3'
>    )
> 
> ... we can remove them. But I personally don't see a problem with those extra lines of code.

Yes. My problem is with this extra sugar. In particular because it turns out to be less powerful. What if we want to prepend sometimes and append other times. Or completly override.

I also would prefer we don't use decorators if we don't need to. My take is that we don't need that yet. The reason is the more features we use, the harder is for people to understand what is going on. Simplicity is not how the code looks, but being able to understand how it works.

I've updated the code to use a dictionary and get rid of the one extra function, replace it with converting the data back and commentary to explain how we deviate from Waf convention.

Essentially we are writing the same code, but I'm optimizing for less code being written by us (and less features) and you are optimizing for nicer call-site syntax.

**Comment by cmarcelo** [comment]
> Essentially we are writing the same code, but I'm optimizing for less code being written by us (and less features) and you are optimizing for nicer call-site syntax.

This might sound bad, I didn't mean to be rude here. Both are valid design decisions, we just disagree about their relative value :-)

**Comment by guludo** [comment]
> > Essentially we are writing the same code, but I'm optimizing for less code being written by us (and less features) and you are optimizing for nicer call-site syntax.
> 
> This might sound bad, I didn't mean to be rude here. Both are valid design decisions, we just disagree about their relative value :-)

I didn't take that as rude at all :-)

**Comment by guludo** [comment]
> The reason is the more features we use, the harder is for people to understand what is going on. Simplicity is not how the code looks, but being able to understand how it works.

I think that depends a lot on how features are implemented, organized and documented :-)

**Pull request closed without merging**
